# Generated by Django 4.0.2 on 2022-02-07 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Name of book publisher", max_length=50),
                ),
                ("website", models.URLField()),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
