# Generated by Django 4.0.2 on 2022-02-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_book_contributor_review_bookcontributor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="publication_date",
            field=models.DateField(default=None, verbose_name="Date the book was published."),
        ),
    ]
